config/routes.rb
Rails.application.routes.draw do
  
  # get 'book/new'
  # get 'book/edit'
  # get 'book/destroy'
  # get 'admin/new'
  # get 'admin/create'
  # get 'admin/destroy'
  #  get 'home/index'
   root 'home#index'
  # get 'admin/index'
  # get 'admin/destory'
  # get 'sessions/new'
  # get 'sessions/create'
  # get 'sessions/destroy'
  resources :users
  resources :sessions, only:[:new,:create,:destroy]
  get 'signup', to: 'users#new', as: 'signup'
  get 'login', to: 'sessions#new', as: 'login'
  get 'logout', to: 'sessions#destroy', as: 'logout'

  get 'reserve/:id', to: 'home#reserve'
  get 'cancel/:id', to: 'home#cancel'

  resources :admin, only:[:new ,:create]
  get 'admin_logout', to: 'admin#destroy', as: 'admin_logout'
  get 'admin', to: 'admin#new', as: 'admin'
  get 'admin_login', to: 'admin#index', as: 'admin_login'

  get '/book/add', to: 'book#new'
  get '/book/create', to: 'book#create'
  get '/book/edit/:id', to: 'book#edit'
  delete '/book/:id', to: 'book#destroy'

  get '/book/r_user', to: 'book#r_user'
  get '/r_list', to: 'home#r_list'
  get '/search', to: 'home#search' 

  post 'update/:id', to: 'book#update'

  # API
  get 'api/books' ,to: 'api/version1#books'
  get 'api/books/:id',to: 'api/version1#show'
  get 'api/reserve/:id', to: 'api/version1#reserve'
  # get 'api/cancel/:id', to: 'api/version1#cancel'
  get 'api/search', to: 'api/version1#search' 
  get 'api/r_list', to: 'api/version1#r_list'
  get 'api/login', to: 'api/version1#login'
  get 'api/logout/:id', to: 'api/version1#logout'
  post 'api/register', to: 'api/version1#register'

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/views/admin/index.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
	<div class="container">
	<a class="navbar-brand" href="#"><h3><b>Zwenex Bookshop</b></h3></a>
	  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
	    <span class="navbar-toggler-icon"></span>
	  </button>

	  <div class="collapse navbar-collapse" id="navbarSupportedContent">
	    <ul class="navbar-nav ml-auto">
	    <% if current_admin %>		
		  <li class="nav-item">	      	
	      	<b><a href="#" class="nav-link" style="text-transform: uppercase;">Welcome '<%= current_admin.name %>'</a></b>
	      </li>
	      <li class="nav-item ">
	        <b><%= link_to 'Log Out',admin_logout_path , class:"nav-link" %> </b>
	      </li>
	    <% end %>
	    </ul>
	  </div>
	</div>
</nav>
<div class="container">
	<p id='notice'><%= notice %></p>

	<br>
	<h3><b>BOOK LISTS</b></h3>
	<br>
	<p align="right"><a href="/book/r_user" class="btn btn-ouline-info">Reserved user list</a></p>
	<div style="height: 5px;"></div>
	<table class="table">
		<tr>
			<th>Title</th>
			<th>Author</th>
			<th>Price</th>
			<th>Published Year</th>
			<th>Category</th>
			<th>Other</th>
		</tr>
		<% @book.each do |b| %>
		<tr>
			<td><%= b.title %></td>
			<td><%= b.author %></td>
			<td><%= b.price %></td>
			<td><%= b.p_year %></td>
			<td><%= b.category %></td>
			<td><a href="/book/edit/<%= b.id %>" class="btn btn-info">Edit</a>
				<a href="/book/<%= b.id %>"  data-method=delete data-confirm="Are you sure?" class="btn btn-danger">Del</a></td>
		</tr>
		<% end %>
	</table>
	<br>
	<a href="/book/add" class="btn btn-primary">Add New Book</a>
</div>

app/views/admin/new.html.erb
<div class="container">
	<p id='alert'><%= alert %></p>
	<h3><b>ADMIN LOGIN</b></h3>
	<br>
	<%= form_tag admin_path do |form| %>
	<div class="field">
		<%= label_tag :name  %>
		<%= text_field_tag :name%>
	</div>
	<div class="field">
		<%= label_tag :password %>
		<%= password_field_tag :password %>
	</div>
	<br>
	<div class="actions">
		<%= submit_tag 'Login',class:"btn btn-primary btn-xs" %>
	</div>
	<% end %>

	<br>
	<%= link_to 'Back', root_path %>
</div>