config/routes.rb
Rails.application.routes.draw do
  
  # get 'book/new'
  # get 'book/edit'
  # get 'book/destroy'
  # get 'admin/new'
  # get 'admin/create'
  # get 'admin/destroy'
  #  get 'home/index'
   root 'home#index'
  # get 'admin/index'
  # get 'admin/destory'
  # get 'sessions/new'
  # get 'sessions/create'
  # get 'sessions/destroy'
  resources :users
  resources :sessions, only:[:new,:create,:destroy]
  get 'signup', to: 'users#new', as: 'signup'
  get 'login', to: 'sessions#new', as: 'login'
  get 'logout', to: 'sessions#destroy', as: 'logout'

  get 'reserve/:id', to: 'home#reserve'
  get 'cancel/:id', to: 'home#cancel'

  resources :admin, only:[:new ,:create]
  get 'admin_logout', to: 'admin#destroy', as: 'admin_logout'
  get 'admin', to: 'admin#new', as: 'admin'
  get 'admin_login', to: 'admin#index', as: 'admin_login'

  get '/book/add', to: 'book#new'
  get '/book/create', to: 'book#create'
  get '/book/edit/:id', to: 'book#edit'
  delete '/book/:id', to: 'book#destroy'

  get '/book/r_user', to: 'book#r_user'
  get '/r_list', to: 'home#r_list'
  get '/search', to: 'home#search' 

  post 'update/:id', to: 'book#update'

  # API
  get 'api/books' ,to: 'api/version1#books'
  get 'api/books/:id',to: 'api/version1#show'
  get 'api/reserve/:id', to: 'api/version1#reserve'
  # get 'api/cancel/:id', to: 'api/version1#cancel'
  get 'api/search', to: 'api/version1#search' 
  get 'api/r_list', to: 'api/version1#r_list'
  get 'api/login', to: 'api/version1#login'
  get 'api/logout/:id', to: 'api/version1#logout'
  post 'api/register', to: 'api/version1#register'

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/book.rb
class Book < ApplicationRecord
end

app/controllers/book_controller.rb
class BookController < ApplicationController
  skip_before_action :require_login, only: [:new]
  def new
  	
  end
  def create
    	book = Book.new(book_params)
  	if book.save
  		redirect_to admin_login_url 
  	else
  		flash[:errors] = book.errors.full_messages
  		redirect_to "/book/add"	
  	end
  end

  def edit
  	@book = Book.find(params[:id])
  end

  def destroy
  	book = Book.find(params[:id])
	book.destroy
	redirect_to admin_login_url
  end
  def r_user
  	@user = Book.where(r_status:"yes")
  end

  def update
    book = Book.find(params[:id])
    if book.update(book_params)
      redirect_to admin_login_url
    else
    flash.now[:alert] = "Update Error!"
    redirect_to admin_login_url 
    end 
  end

  private
  	def book_params
  		params.require(:book).permit(:title,:author,:p_year,:price,:category,:r_status,:img)
  	end
end

app/helpers/ap1/v1/books_helper.rb
module Ap1::V1::BooksHelper
end

app/helpers/book_helper.rb
module BookHelper
end

app/views/book/edit.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
	<div class="container">
	<a class="navbar-brand" href="#"><h3><b>Zwenex Bookshop</b></h3></a>
	  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
	    <span class="navbar-toggler-icon"></span>
	  </button>

	  <div class="collapse navbar-collapse" id="navbarSupportedContent">
	    <ul class="navbar-nav ml-auto">
	    <% if current_admin %>		
		  <li class="nav-item">	      	
	      	<b><a href="#" class="nav-link" style="text-transform: uppercase;">Welcome '<%= current_admin.name %>'</a></b>
	      </li>
	      <li class="nav-item ">
	        <b><%= link_to 'Log Out',admin_logout_path , class:"nav-link" %> </b>
	      </li>
	    <% end %>
	    </ul>
	  </div>
	</div>
</nav>
<br><br>
<div class="container">
	<h3>Edti Book</h3>
	<br>
		<form action="/update/<%= @book.id %>" method="post">
		<input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
	  <div class="form-group row">
	    <label for="staticEmail" class="col-sm-2 col-form-label">Title :</label>
	    <div class="col-sm-10">
	      <input type="text" class="form-control" id="staticEmail" name="book[title]" value="<%= @book.title %>">
	    </div>
	  </div>
	  <div class="form-group row">
	    <label for="author" class="col-sm-2 col-form-label">Author :</label>
	    <div class="col-sm-10">
	      <input type="text" class="form-control" id="author" name="book[author]" value="<%= @book.author %>">
	    </div>
	  </div>
	  <div class="form-group row">
	    <label for="price" class="col-sm-2 col-form-label">Price :</label>
	    <div class="col-sm-10">
	      <input type="text" class="form-control" id="price" name="book[price]" value="<%= @book.price %>">
	    </div>
	  </div>
	  <div class="form-group row">
	    <label for="p_year" class="col-sm-2 col-form-label">Published Year :</label>
	    <div class="col-sm-10">
	      <input type="text" class="form-control" id="p_year" name="book[p_year]" value="<%= @book.p_year %>">
	    </div>
	  </div>
	  <div class="form-group row">
	    <label for="category" class="col-sm-2 col-form-label">Category :</label>
	    <div class="col-sm-10">
	      <input type="text" class="form-control" id="category" name="book[category]" value="<%= @book.category %>">
	    </div>
	  </div>
	  <div class="form-group row">
	    <label for="img" class="col-sm-2 col-form-label">Image :</label>
	    <div class="col-sm-10">
	      <input type="file" id="img" name="book[img]" value="<%= @book.img %>">
	    </div>
	  </div>
	  <br>
  	  <button type="submit" class="btn btn-primary" style="padding: 6px 20px;">Update Book</button>
	  <%= link_to 'Back', admin_login_url ,class:"btn btn-danger"%>
	  
	</form>
	
</div>

app/views/book/new.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
	<div class="container">
	<a class="navbar-brand" href="#"><h3><b>Zwenex Bookshop</b></h3></a>
	  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
	    <span class="navbar-toggler-icon"></span>
	  </button>

	  <div class="collapse navbar-collapse" id="navbarSupportedContent">
	    <ul class="navbar-nav ml-auto">
	    <% if current_admin %>		
		  <li class="nav-item">	      	
	      	<b><a href="#" class="nav-link" style="text-transform: uppercase;">Welcome '<%= current_admin.name %>'</a></b>
	      </li>
	      <li class="nav-item ">
	        <b><%= link_to 'Log Out',admin_logout_path , class:"nav-link" %> </b>
	      </li>
	    <% end %>
	    </ul>
	  </div>
	</div>
</nav>
<br><br>
<div class="container">
	<h3><b>ADD NEW BOOK</b></h3>
	<br>
	<form action="/book/create" method="get">
		<input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
	  <div class="form-group row">
	    <label for="staticEmail" class="col-sm-2 col-form-label">Title :</label>
	    <div class="col-sm-10">
	      <input type="text" class="form-control" id="staticEmail" name="book[title]" required>
	    </div>
	  </div>
	  <div class="form-group row">
	    <label for="author" class="col-sm-2 col-form-label">Author :</label>
	    <div class="col-sm-10">
	      <input type="text" class="form-control" id="author" name="book[author]" required>
	    </div>
	  </div>
	  <div class="form-group row">
	    <label for="price" class="col-sm-2 col-form-label">Price :</label>
	    <div class="col-sm-10">
	      <input type="text" class="form-control" id="price" name="book[price]" required>
	    </div>
	  </div>
	  <div class="form-group row">
	    <label for="p_year" class="col-sm-2 col-form-label">Published Year :</label>
	    <div class="col-sm-10">
	      <input type="text" class="form-control" id="p_year" name="book[p_year]" required>
	    </div>
	  </div>
	  <div class="form-group row">
	    <label for="category" class="col-sm-2 col-form-label">Category :</label>
	    <div class="col-sm-10">
	      <input type="text" class="form-control" id="category" name="book[category]" required>
	    </div>
	  </div>
	  <div class="form-group row">
	    <label for="img" class="col-sm-2 col-form-label">Image :</label>
	    <div class="col-sm-10">
	      <input type="file" id="img" name="book[img]" required>
	    </div>
	  </div>
	  <input type="hidden" name="book[r_status]" value="no" >
	  <br>
  	  <button type="submit" class="btn btn-primary" style="padding: 6px 20px;">Add Book</button>
	  <%= link_to 'Back', admin_login_url ,class:"btn btn-danger"%>
	</form>
	<br>
	
</div>

app/views/book/r_user.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
	<div class="container">
	<a class="navbar-brand" href="#"><h3><b>Zwenex Bookshop</b></h3></a>
	  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
	    <span class="navbar-toggler-icon"></span>
	  </button>

	  <div class="collapse navbar-collapse" id="navbarSupportedContent">
	    <ul class="navbar-nav ml-auto">
	    <% if current_admin %>		
		  <li class="nav-item">	      	
	      	<b><a href="#" class="nav-link" style="text-transform: uppercase;">Welcome '<%= current_admin.name %>'</a></b>
	      </li>
	      <li class="nav-item ">
	        <b><%= link_to 'Log Out',admin_logout_path , class:"nav-link" %> </b>
	      </li>
	    <% end %>
	    </ul>
	  </div>
	</div>
</nav>
<br>
<br>
<div class="container">
	<h3><b>Reserved User Lists</b></h3>
	<table class="table">
		<tr>
			<th>Username</th>
			<th>Book Title</th>
			<th>Others</th>
		</tr>
		<% @user.each do |u|%>
		<tr>
			<td><%= u.r_user %></td>
			<td><%= u.title %></td>
			<td><a href="/r_cancel/<%= u.id %>" class="btn btn-danger">Cancel</a></td>
		</tr>
		<% end %>
	</table>
	<br>
	<%= link_to "Back",admin_login_path%>
</div>