config/routes.rb
Rails.application.routes.draw do
  
  # get 'book/new'
  # get 'book/edit'
  # get 'book/destroy'
  # get 'admin/new'
  # get 'admin/create'
  # get 'admin/destroy'
  #  get 'home/index'
   root 'home#index'
  # get 'admin/index'
  # get 'admin/destory'
  # get 'sessions/new'
  # get 'sessions/create'
  # get 'sessions/destroy'
  resources :users
  resources :sessions, only:[:new,:create,:destroy]
  get 'signup', to: 'users#new', as: 'signup'
  get 'login', to: 'sessions#new', as: 'login'
  get 'logout', to: 'sessions#destroy', as: 'logout'

  get 'reserve/:id', to: 'home#reserve'
  get 'cancel/:id', to: 'home#cancel'

  resources :admin, only:[:new ,:create]
  get 'admin_logout', to: 'admin#destroy', as: 'admin_logout'
  get 'admin', to: 'admin#new', as: 'admin'
  get 'admin_login', to: 'admin#index', as: 'admin_login'

  get '/book/add', to: 'book#new'
  get '/book/create', to: 'book#create'
  get '/book/edit/:id', to: 'book#edit'
  delete '/book/:id', to: 'book#destroy'

  get '/book/r_user', to: 'book#r_user'
  get '/r_list', to: 'home#r_list'
  get '/search', to: 'home#search' 

  post 'update/:id', to: 'book#update'

  # API
  get 'api/books' ,to: 'api/version1#books'
  get 'api/books/:id',to: 'api/version1#show'
  get 'api/reserve/:id', to: 'api/version1#reserve'
  # get 'api/cancel/:id', to: 'api/version1#cancel'
  get 'api/search', to: 'api/version1#search' 
  get 'api/r_list', to: 'api/version1#r_list'
  get 'api/login', to: 'api/version1#login'
  get 'api/logout/:id', to: 'api/version1#logout'
  post 'api/register', to: 'api/version1#register'

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  skip_before_action :require_login, only:[:index,:reserve,:cancel,:r_list,:search]
  def index
  	@books = Book.all
  end

  def reserve
  	book = Book.find(params[:id])
  	if book.update(r_status:"yes",r_user: current_user.id)
		  redirect_to root_url
	  else
		flash.now[:alert] = "Error!"
		redirect_to root_url	
	end
  end
  def cancel
 	book = Book.find (params[:id])
   	if book.update(r_status:"no",r_user: " ")
   		redirect_to root_url
   	else
  		flash.now[:alert] = "Error!"
  		redirect_to root_url	
   	end
  end

  def r_list
    @list = Book.where(r_user:current_user.id)
  end

  def search
    @books = Book.where("lower(category) LIKE :search", {search: "%#{params[:search].downcase}%"})
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/index.html.erb
<nav class="navbar navbar-expand-lg navbar-dark " style="background:#428bca;">
	<div class="container">
	<a class="navbar-brand" href="#"><h3><b>Zwenex Bookshop</b></h3></a>
	  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
	    <span class="navbar-toggler-icon"></span>
	  </button>

	  <div class="collapse navbar-collapse" id="navbarSupportedContent">
	    <ul class="navbar-nav ml-auto">
	    <% if current_user %>		
		  <li class="nav-item">	      	
	      	<b><a href="#" class="nav-link" style="text-transform: uppercase;">Welcome '<%= current_user.name %>'</a></b>
	      </li>
	      <li class="nav-item ">
	        <b><%= link_to 'Log Out',logout_path , class:"nav-link" %> </b>
	      </li>
		<% else %>
	      <li class="nav-item">	      	
	      	<b><%= link_to 'Log In',login_path, class:"nav-link" %> </b>
	      </li>
	      <li class="nav-item ">
	        <b><%= link_to 'Sign up',signup_path, class:"nav-link" %> </b>
	      </li>
	    <% end %>
	    </ul>
	  </div>
	</div>
</nav>
<br><br>
<div class="container">
<p id="notice"><%= notice %></p>

<h4 style="font-weight: bold;text-transform: uppercase;">Book list</h4>

<form method="get" action="/search">
      <div class="row">
      	<div class="col-md-11">
      		<input class="form-control mr-sm-2" type="search" placeholder="Search Book Category" aria-label="Search" name="search"> 
      	</div>
      	<div class="col-md-1">
      		 <button class="btn btn-outline-danger" type="submit">Search</button>
      	</div>
      </div>
</form>
<br>
<% if current_user%>
	<a href="/r_list" class="btn btn-outline-primary">Reserved list</a></p>
<% end%>
<p>
<br>
<div class="row">

	<% @books.each do |b| %>


	<div class="col-md-3">
		<a href="#">
			<div class="card">
			  <img class="card-img-top" src="images/<%= b.img %>" alt="Card image cap">
			  <div class="card-body">
			    <h6 class="card-title" style="color: #000;">Title : <b><%= b.title %></b></h6>	    
			    <p class="card-title" style="color: #000;">Category : <b><%= b.category %></b></p> 
			    <p class="card-title" style="color: #000;">Price : <b>$ <%= b.price %></b></p>	    
			  </div>
			</div>
		</a>
		<div style="height: 10px;"></div>

		<% if current_user %>
			<% if b.r_status == "no" %>
				<a href="/reserve/<%= b.id %>"><button class="btn btn-xs btn-info" style="width: 100%;">Reserve</button></a>
			<% elsif b.r_status == "yes" && b.r_user = current_user.id %>
				<a href="/cancel/<%= b.id %>"><button class="btn btn-xs btn-danger" style="width: 100%;">Cancel</button></a>			<% else %>
			<button class="btn btn-xs btn-default" disabled  style="width: 100%;"> Reserved</button> 
			<% end %>
		<% end %>

			<% if current_user%>
			<button class="btn btn-xs btn-default" style="width: 100%;display:none;">Please login for reserve!</button> 
			<% else %>
			<button class="btn btn-xs btn-default" disabled  style="width: 100%;">Please login for reserve!</button> 
			
			<% end%>
			<div style="height: 25px;"></div>
	</div>

	<% end %>
</div>
</div>

app/views/home/r_list.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
	<div class="container">
	<a class="navbar-brand" href="#"><h3><b>Zwenex Bookshop</b></h3></a>
	  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
	    <span class="navbar-toggler-icon"></span>
	  </button>

	  <div class="collapse navbar-collapse" id="navbarSupportedContent">
	    <ul class="navbar-nav ml-auto">
	    <% if current_user %>		
		  <li class="nav-item">	      	
	      	<b><a href="#" class="nav-link" style="text-transform: uppercase;">Welcome '<%= current_user.name %>'</a></b>
	      </li>
	      <li class="nav-item ">
	        <b><%= link_to 'Log Out',logout_path , class:"nav-link" %> </b>
	      </li>
		<% else %>
	      <li class="nav-item">	      	
	      	<b><%= link_to 'Log In',login_path, class:"nav-link" %> </b>
	      </li>
	      <li class="nav-item ">
	        <b><%= link_to 'Sign up',signup_path, class:"nav-link" %> </b>
	      </li>
	    <% end %>
	    </ul>
	  </div>
	</div>
</nav>
<br><br>
<div class="container">
	<h3>MY RESERVE LIST</h3>
	<br>
	<table class="table">
		<tr>
			<th>Title</th>
			<th>Author</th>
			<th>Price</th>
			<th>Published Year</th>
			<th>Category</th>
			<th>OTHER</th>
		</tr>
		<% @list.each do |l| %>
		<tr>
			<td><%= l.title %></td>
			<td><%= l.author %></td>
			<td><%= l.price %></td>
			<td><%= l.p_year %></td>
			<td><%= l.category %></td>
			<td><a href="/cancel/<%= l.id %>" class="btn btn-danger">Cancel</a></td>
		</tr>
		<% end %>
	</table>
	<br>
	<%= link_to "Back", root_path %>
</div>

app/views/home/search.html.erb
<nav class="navbar navbar-expand-lg navbar-dark" style="background:#428bca;">
	<div class="container">
	<a class="navbar-brand" href="#"><h3><b>Zwenex Bookshop</b></h3></a>
	  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
	    <span class="navbar-toggler-icon"></span>
	  </button>

	  <div class="collapse navbar-collapse" id="navbarSupportedContent">
	    <ul class="navbar-nav ml-auto">
	    <% if current_user %>		
		  <li class="nav-item">	      	
	      	<b><a href="#" class="nav-link" style="text-transform: uppercase;">Welcome '<%= current_user.name %>'</a></b>
	      </li>
	      <li class="nav-item ">
	        <b><%= link_to 'Log Out',logout_path , class:"nav-link" %> </b>
	      </li>
		<% else %>
	      <li class="nav-item">	      	
	      	<b><%= link_to 'Log In',login_path, class:"nav-link" %> </b>
	      </li>
	      <li class="nav-item ">
	        <b><%= link_to 'Sign up',signup_path, class:"nav-link" %> </b>
	      </li>
	    <% end %>
	    </ul>
	  </div>
	</div>
</nav>
<br><br>
<div class="container">
<p id="notice"><%= notice %></p>

<h4 style="font-weight: bold;text-transform: uppercase;">Book list</h4>

<form method="get" action="/search">
      <div class="row">
      	<div class="col-md-11">
      		<input class="form-control mr-sm-2" type="search" placeholder="Search Book Category" aria-label="Search" name="search"> 
      	</div>
      	<div class="col-md-1">
      		 <button class="btn btn-outline-danger" type="submit">Search</button>
      	</div>
      </div>
</form>
<br>
<% if current_user%>
	<a href="/r_list" class="btn btn-outline-primary">Reserved list</a></p>
<% end%>
<p>
<br>
<div class="row">

	<% @books.each do |b| %>


	<div class="col-md-3">
		<a href="#">
			<div class="card">
			  <img class="card-img-top" src="images/<%= b.img %>" alt="Card image cap">
			  <div class="card-body">
			    <h6 class="card-title" style="color: #000;">Title : <b><%= b.title %></b></h6>	    
			    <p class="card-title" style="color: #000;">Category : <b><%= b.category %></b></p> 
			    <p class="card-title" style="color: #000;">Price : <b>$ <%= b.price %></b></p>	    
			  </div>
			</div>
		</a>
		<div style="height: 10px;"></div>

		<% if current_user %>
			<% if b.r_status == "no" %>
				<a href="/reserve/<%= b.id %>"><button class="btn btn-xs btn-info" style="width: 100%;">Reserve</button></a>
			<% elsif b.r_status == "yes" && b.r_user == current_user.name %>
				<a href="/cancel/<%= b.id %>"><button class="btn btn-xs btn-danger" style="width: 100%;">Cancel</button></a>			<% else %>
			<button class="btn btn-xs btn-default" disabled  style="width: 100%;"> Reserved</button> 
			<% end %>
		<% end %>

			<% if current_user%>
			<button class="btn btn-xs btn-default" style="width: 100%;display:none;">Please login for reserve!</button> 
			<% else %>
			<button class="btn btn-xs btn-default" disabled  style="width: 100%;">Please login for reserve!</button> 
			
			<% end%>
			<div style="height: 25px;"></div>
	</div>

	<% end %>
</div>
</div>